<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="B107DCOK" ignored="0" name="Run All Tests" tests="4" failures="1" timestamp="02 Aug 2018 14:18:33 GMT" time="34.909" errors="0">
  <testcase name="feature" time="3.811" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="2.305" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="2.754" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="23.411" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionErrorat cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: java.lang.AssertionErrorat org.junit.Assert.fail(Assert.java:86)at org.junit.Assert.fail(Assert.java:95)at wrappers.Generic.enterTextById(Generic.java:150)at stepDefinition.Trello.i_entered_my_and(Trello.java:27)at âœ½.When I entered my "azharw49@gmail.com" and "Chelsea@1"(./features/TrelloLogin.feature:5)]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Run All Tests -->
